;-*-unibyte: t;-*-
;;;; the line above is needed for Emacs 20.3 -- without it,character ranges
;;;; for characters between \200 and \377 don't work
 
(defun tex-2-iso-latin1 ()
  (interactive)
  (let ((case-replace     t)
        (case-fold-search nil)
       )
    (lse-tpu:replace-all "\\\\\"A"       "Ä")
    (lse-tpu:replace-all "\"A"           "Ä")
    (lse-tpu:replace-all "\\\\\"a"       "ä")
    (lse-tpu:replace-all "\"a"           "ä")
    (lse-tpu:replace-all "\\\\\"O"       "Ö")
    (lse-tpu:replace-all "\"O"           "Ö")
    (lse-tpu:replace-all "\\\\\"o"       "ö")
    (lse-tpu:replace-all "\"o"           "ö")
    (lse-tpu:replace-all "\\\\\"U"       "Ü")
    (lse-tpu:replace-all "\"U"           "Ü")
    (lse-tpu:replace-all "\\\\\"u"       "ü")
    (lse-tpu:replace-all "\"u"           "ü")
    (lse-tpu:replace-all "\\\\ss"        "ß")
    (lse-tpu:replace-all "\"s"           "ß")
    (lse-tpu:replace-all "\\\\AA"        "Å")
    (lse-tpu:replace-all "\\\\AE"        "Æ")
    (lse-tpu:replace-all "\\\\c C"       "Ç")
    (lse-tpu:replace-all "\\\\'E"        "É")
    (lse-tpu:replace-all "\\\\~N"        "Ñ")
    (lse-tpu:replace-all "\\\\`a"        "à")
    (lse-tpu:replace-all "\\\\'a"        "á")
    (lse-tpu:replace-all "\\\\^a"        "â")
    (lse-tpu:replace-all "\\\\aa"        "å")
    (lse-tpu:replace-all "\\\\ae"        "æ")
    (lse-tpu:replace-all "\\\\c c"       "ç")
    (lse-tpu:replace-all "\\\\`e"        "è")
    (lse-tpu:replace-all "\\\\'e"        "é")
    (lse-tpu:replace-all "\\\\^e"        "ê")
    (lse-tpu:replace-all "\\\\\"e"       "ë")
    (lse-tpu:replace-all "\"e"           "ë")
    (lse-tpu:replace-all "\\\\`\\\\i"    "ì")
    (lse-tpu:replace-all "\\\\'\\\\i"    "í")
    (lse-tpu:replace-all "\\\\^\\\\i"    "î")
    (lse-tpu:replace-all "\\\\\"\\\\i"   "ï")
    (lse-tpu:replace-all "\"\\\\i"       "ï")
    (lse-tpu:replace-all "\\\\~n"        "ñ")
    (lse-tpu:replace-all "\\\\`o"        "ò")
    (lse-tpu:replace-all "\\\\'o"        "ó")
    (lse-tpu:replace-all "\\\\^o"        "ô")
    (lse-tpu:replace-all "\\\\`u"        "ù")
    (lse-tpu:replace-all "\\\\'u"        "ú")
    (lse-tpu:replace-all "\\\\^u"        "û")
    (lse-tpu:replace-all "!`"            "¡")
    (lse-tpu:replace-all "?`"            "¿")
    (lse-tpu:replace-all "\\\\pounds"    "£")
    (lse-tpu:replace-all "\\\\S "        "§")
    (lse-tpu:replace-all "\\\\P "        "¶")
  )
)
;;; (setq debug-on-error nil)
