#! /swing/bin/bash
# Copyright (C) 2011 Mag. Christian Tanzer All rights reserved
# Glasauergasse 32, A--1130 Wien, Austria. tanzer@swing.co.at
# #*** <License> ************************************************************
# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This script is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script. If not, see <http://www.gnu.org/licenses/>.
# #*** </License> ***********************************************************#
#
#++
# Name
#    lse_compile_elisp
#
# Purpose
#    Compile elisp files of ls-emacs
#
# Revision Dates
#    18-May-2011 (CT) Creation
#    ««revision-date»»···
#--

if [ -z "$EMACSLSESRC" ]
then
    source $(dirname $0)/ls-emacs-ini.bash
fi

emacs_cmd="(setq load-path (append (list \"$LSE_USER_PREFIX\" \"/usr/share/emacs/site-lisp/javascript\") load-path)) (load \"ls-emacs\") (lse-byte-compile:all \"$@\")"
cmd_file="/tmp/lse_compile_elisp_$$"
echo "${emacs_cmd}"  > "${cmd_file}" \
    && emacs -batch -l "${cmd_file}" \
    && rm              "${cmd_file}"

### __END__ lse_compile_elisp
